#!/bin/bash

function obter_informacoes {
    read -p "Digite o email do Administrador: " EMAIL_ADMINISTRADOR
    read -p "Digite o domínio para o Traefik: " DOMINIO_TRAEFIK
    read -p "Digite o domínio para o Portainer: " DOMINIO_PORTAINER
    read -p "Digite o domínio para o Edge: " DOMINIO_EDGE
    read -p "Digite a senha para o Traefik: " SENHA_TRAEFIK
}

function instalar_typebot {
    
    sudo apt update -y
    sudo apt upgrade -y
    sudo apt-add-repository universe

    # Dependências
    sudo apt install -y python2-minimal nodejs npm git curl apt-transport-https ca-certificates software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    sudo apt update
    sudo apt install -y docker-ce docker-compose

    # Adicionar o usuário usuário ao grupo Docker
    sudo usermod -aG docker ${USER}
    
    obter_informacoes    

    # Arquivo docker-compose.yml usando as informações
    cat <<EOF > docker-compose.yml

version: "3.8"

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"
    restart: always
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
      - --log.level=ERROR
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.email=${EMAIL_ADMINISTRADOR} #Defina aqui seu endereço de e-mail, é para geração de certificados SSL com Let's Encrypt. 
      - --certificatesresolvers.leresolver.acme.storage=./acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`${DOMINIO_TRAEFIK}`)" #Coloque o Seu Dominio do Traefik Aqui
      - "traefik.http.routers.traefik-dashboard.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=leresolver"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${SENHA_TRAEFIK}" #Coloque a Senha do Traefik Aqui Nao Remova As Aspas
      - "traefik.http.routers.traefik-dashboard.middlewares=traefik-auth"

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMINIO_PORTAINER}`)" #Coloque o Seu Dominio do Portainer Aqui
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`${DOMINIO_EDGE}`)" #Coloque o Seu Dominio do Edge Aqui
      - "traefik.http.routers.edge.entrypoints=websecure"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=leresolver"


volumes:
  portainer_data:

EOF

    # Inicia os contêineres
    docker-compose up -d    

    echo "Portainer instalado com sucesso!"
}

instalar_typebot
